#!/bin/sh

# Usage:
#
# If phpbb-merge was used previously, simply:
# phpbb-merge-develop

set -e

branch="$1"
pr="$2"
target="$3"

if test -z "$pr"; then
	if test -f $HOME/.phpbb-merge-state; then
		# freebsd's /bin/sh creates a new environment when
		# reading in a pipe, which causes echo foo |read bar
		# to effectively discard the read operation.
		# use awk to work around this
		pr=`awk '{print $2}' <$HOME/.phpbb-merge-state`
		branch=`awk '{print $3}' <$HOME/.phpbb-merge-state`
	fi
fi

if test -z "$pr"; then
	echo "Usage: `basename $0` branch PR" 1>&2
	exit 5
fi

if test -z "$target"; then
	target=develop
fi

echo "Merging $branch into $target for PR #$pr"

current_branch=`git branch |grep '^\*' |awk '{print $2}'`

if test "$current_branch" != "$target"; then
	git checkout "$target"
fi

git merge --no-ff "$branch"

git filter-branch  --msg-filter \
	"sed -e 's/^Merge branch/Merge PR #$pr branch/'" \
	-f -- --max-count=1 HEAD

rm -f $HOME/.phpbb-merge-state
