#!/usr/bin/env perl

use strict;

die "Usage: phpbb-reformat [-2|-8] [-i] file ..." unless @ARGV;

my $indent = undef;
my $ignore = 0;

while (@ARGV > 0 && $ARGV[0] =~ /^-/) {
    if ($ARGV[0] eq '-8') {
        $indent = 8;
        shift @ARGV;
    } elsif ($ARGV[0] eq '-2') {
        $indent = 2;
        shift @ARGV;
    } elsif ($ARGV[0] eq '-i') {
        $ignore = 1;
        shift @ARGV;
    } else {
        warn "Unrecognized option: $ARGV[0]\n";
        exit 5;
    }
}

undef $/;
for my $file (@ARGV) {
    # strip leading a/ or b/
    $file =~ s.^[ab]/..;
    
    if (!open FH, $file) {
        if ($ignore) {
            warn "Can't open file for reading: $file";
            next;
        } else {
            die "Can't open file for reading: $file";
        }
    }
    $_ = <FH>;
    close FH;
    
    my $rep;
    if ($indent) {
        $rep = $indent;
    } else {
        if (/^  {1,3}\S/m) {
            $rep = 2;
        } else {
            $rep = 8;
        }
    }
    
    s|^(( {$rep})+)|"\t" x (length($1) / $rep)|gem;
    s|^(\t*)(.*) \{$|$1$2\n${1}{|gm;
    s/^(\t*)} (else|catch)/\1}\n\1\2/gm;
    s/^(\t*)$//gm;
    
    open FH, ">$file" or die "Can't open file for writing: $file";
    print FH $_;
    print $rep;
    close FH;
}
