#!/bin/sh

set -e

usage() {
	echo "Usage: `basename $0` [-F]" 1>&2
	exit 5
}

fetch=true

while getopts :F option; do
	case $option in
	F)
		fetch=false;;
	*)
		usage;;
	esac
done

branch=`git branch --contains HEAD |head -1 |awk '{print $2}'`

if $fetch; then
	git fetch upstream
fi
git checkout develop-olympus
git reset --hard upstream/develop-olympus
git checkout develop
git reset --hard upstream/develop

git checkout "$branch"
