#!/usr/bin/env perl

package main;

use strict;
use warnings;
use PHPBB::Checker;

my $branch = shift @ARGV;
my $into_prefix = '';

unless ($branch) {
    $branch = 'HEAD';
    $into_prefix = 'upstream/';
}

my ($branch_commits, $branch_meta) = PHPBB::Checker::shortlog($branch);
my @branch_commits = @{$branch_commits};
my $develop_commit = PHPBB::Checker::head_commit($into_prefix . 'develop');
my $olympus_commit = PHPBB::Checker::head_commit($into_prefix . 'develop-olympus');

my $into = '';
foreach my $sha (@branch_commits) {
    if ($sha eq $develop_commit) {
        $into = $into_prefix . 'develop';
        last;
    } elsif ($sha eq $olympus_commit) {
        $into = $into_prefix . 'develop-olympus';
        last;
    }
}

die "Could not determine merge target" unless $into;

print "Checking $branch for merge into $into\n";

my @base_commits = PHPBB::Checker::commits_in_branch($into);
my %base_hash = ();
foreach my $sha (@base_commits) {
    $base_hash{$sha} = 1;
}
my @delta_commits = ();
foreach my $sha (@branch_commits) {
    unless ($base_hash{$sha}) {
        push @delta_commits, $sha;
    }
}

print "Commits:\n";
foreach my $sha (@delta_commits) {
    print $branch_meta->{$sha};
}

foreach my $sha (@delta_commits) {
    PHPBB::Checker::check_commit $sha;
}
