#!/usr/bin/env perl

die "Usage: reformat-phpbb file ..." unless @ARGV;

undef $/;
for $file (@ARGV) {
    open FH, $file or die "Can't open file for reading: $file";
    $_ = <FH>;
    close FH;
    
    if (/^  {1,3}\S/m) {
        $rep = 2;
    } else {
        $rep = 8;
    }
    s|^(( {$rep})+)|"\t" x (length($1) / $rep)|gem;
    s|^(\t*)(.*) \{$|$1$2\n${1}{|gm;
    s/^(\t*)} else(\n|\$)/\1}\n\1else\2/gm;
    s/^(\t*)$//gm;
    
    open FH, ">$file" or die "Can't open file for writing: $file";
    print FH $_;
    #print $rep;
    close FH;
}
