#!/bin/sh

version="$1"

test -z "$version" && {
	echo "Usage: $0 version" 1>&2
	exit 5
}

./configure --prefix=$HOME/opt/php$version \
	--enable-fpm \
	--with-pdo-pgsql=/usr/local \
	--with-mysql=/usr/local \
	--with-pdo-mysql=/usr/local \
	--with-curl=/usr/local

# additional extensions:
#
# zlib
# bz2
# mysql (does not build standalone for some reason)
# pgsql
# pcntl
