#!/bin/sh

set -e

cd
cd test-phpbb
rsync --delete --exclude .git -av  ~/phpbb/ ./

PHPBB_NO_COMPOSER_AUTOLOAD=1 \
PHPBB_AUTOLOAD=~/shared/phpbb_autoload.php \
time php -d include_path=.:/home/pie/apps/git-phpunit-bundle:/home/pie/apps/git-phpbb3-dependencies \
~pie/apps/git-phpunit-bundle/phpunit.php "$@"
