#!/bin/sh

set -e

test -f "$0" && (echo "$0" |grep -q /) || {
	echo "Please invoke with a path." 1>&2
	exit 10
}

export \
phpbb_tools_test_driver_config=phpunit.xml.dist

exec `dirname "$0"`/test-driver "$@"
