#!/bin/sh

set -e

cd
cd test-phpbb
rsync --delete --exclude .git -av  ~/phpbb/ ./

PHPBB_TEST_DBNAME=phpbbtest \
PHPBB_TEST_DBHOST=localhost \
PHPBB_TEST_DBUSER=phpbbtest \
PHPBB_TEST_DBMS=mysqli \
PHPBB_NO_COMPOSER_AUTOLOAD=1 \
PHPBB_AUTOLOAD=~/shared/phpbb_autoload.php \
time php -d include_path=.:/home/pie/apps/git-phpbb/phpunit-bundle:/home/pie/apps/git-phpbb/deps \
~pie/apps/git-phpbb/phpunit-bundle/phpunit.php "$@"
