#!/bin/sh

set -e

test -f "$0" && (echo "$0" |grep -q /) || {
	echo "Please invoke with a path." 1>&2
	exit 10
}

cd
cd test-phpbb
rsync --delete --exclude .git -av  ~/phpbb/ ./

export \
PHPBB_TEST_DBNAME=phpbbtest \
PHPBB_TEST_DBHOST=localhost \
PHPBB_TEST_DBUSER=phpbbtest \
PHPBB_TEST_DBMS=postgres \
PHPBB_NO_COMPOSER_AUTOLOAD=1 \
PHPBB_AUTOLOAD=$HOME/shared/phpbb_autoload.php \
phpbb_tools_test_driver_config=phpunit.xml.dist

exec `dirname "$0"`/test-driver "$@"
