#!/bin/sh

runner=phpdev

###

set -e

base=`dirname $0`

if ! test -d "$base"; then
	echo "Must be invoked with a path" 1>&2
	exit 10
fi

base=`realpath "$base"`
fail=false

for run in "$@"; do
	echo "Runing $run"
	run=`echo "$run" |sed -e s/unit-// -e s/postgres/pg/`
	full="$base"/test-"$run"
	if ! sudo -u "$runner" "$full"; then
		fail=true
	fi
done

if $fail; then
	echo 'Tests failed!'
	exit 19
fi
